version: "3.9"
services:
  backend:
    build: .
    image: backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      CHROMA_DIR: /data/chroma_store
      DB_URL: sqlite:////data/app.db
      OCR_ENABLED: "false"
      ANONYMIZED_TELEMETRY: "false"
      # LLM_PROVIDER: ollama
      # OLLAMA_BASE_URL: http://host.docker.internal:11434
      # For OpenAI:
      # LLM_PROVIDER: openai
      # OPENAI_API_KEY: sk-...
    volumes:
         - ./data:/data
    restart: unless-stopped
